### DISCUSSION TITLE
Kalibr 相机标定

### DISCUSSION THREAD

**Discussion by shu1ong** [shu1ong/Blog#17] [Utils]
在标定时使用其他模型出错，的解决
具体问题为focal length初始化失败了，得手动设定一个值进行初始化
需要设定环境变量
[注意 等号前后不要有空格]
```
export KALIBR_MANUAL_FOCAL_LENGTH_INIT=1
```
然后给定一个初始值即可解决问题（参考链接的是400，我们使用400初始化的结果感觉还不错）

https://github.com/ethz-asl/kalibr/issues/99

```
rosrun kalibr kalibr_calibrate_cameras \
 	--target config/test.yaml \
 	--models pinhole-equi \
 	--topics /umi/camera_hand \
 	--bag sq_shishi1.bag \
 	--bag-freq 5.0
```

**Comment by shu1ong** [comment]
相机标定,一定是为后续的相机模型调用的.在标定之前一定要先确定之后使用的相机模型再回头来确定使用的标定相机模型
这里确定所使用的`vins-mono` 而且使用是`mei`模型 其中config的参数如下所示:
```
#camera calibration  
model_type: MEI
camera_name: camera
image_width: 640 #640
image_height: 480 #480


mirror_parameters:
    xi: 1.1306092528554035
distortion_parameters:
    k1: -0.01881778996352343
    k2: -0.4826354893017739
    p1: 0.0063733658848492145
    p2: 0.004292886765980306
projection_parameters:
    gamma1: 313.13548246957333
    gamma2: 311.970054552347
    u0: 335.0522507922765
    v0: 236.5668332996539
```

对于使用`kalibr`作为标定工具的话,使用 `omni-redtan`正好能够使得参数进行一一对应的输入
- 相机模型参数 (omni):
xi -> mirror_parameters:xi
fu -> projection_parameters:gamma1
fv -> projection_parameters:gamma2
pu -> projection_parameters:u0
pv -> projection_parameters:v0
- 畸变模型参数 (radtan):
k1 -> distortion_parameters:k1
k2 -> distortion_parameters:k2
r1 -> distortion_parameters:p1
r2 -> distortion_parameters:p2
